/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.1 (3.7)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventRuleActionType {
    /// * `webhook` - Webhook * `script` - Script
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl EventRuleActionType {
    pub fn new() -> EventRuleActionType {
        EventRuleActionType {
            value: None,
            label: None,
        }
    }
}

/// * `webhook` - Webhook * `script` - Script
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "webhook")]
    Webhook,
    #[serde(rename = "script")]
    Script,
}

impl Default for Value {
    fn default() -> Value {
        Self::Webhook
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Webhook")]
    Webhook,
    #[serde(rename = "Script")]
    Script,
}

impl Default for Label {
    fn default() -> Label {
        Self::Webhook
    }
}

