/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.1 (3.7)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IpSecProposal : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpSecProposal {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "encryption_algorithm")]
    pub encryption_algorithm: Box<crate::models::IkeProposalEncryptionAlgorithm>,
    #[serde(rename = "authentication_algorithm")]
    pub authentication_algorithm: Box<crate::models::IkeProposalAuthenticationAlgorithm>,
    /// Security association lifetime (seconds)
    #[serde(rename = "sa_lifetime_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sa_lifetime_seconds: Option<Option<i32>>,
    /// Security association lifetime (in kilobytes)
    #[serde(rename = "sa_lifetime_data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sa_lifetime_data: Option<Option<i32>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl IpSecProposal {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, name: String, encryption_algorithm: crate::models::IkeProposalEncryptionAlgorithm, authentication_algorithm: crate::models::IkeProposalAuthenticationAlgorithm, created: Option<String>, last_updated: Option<String>) -> IpSecProposal {
        IpSecProposal {
            id,
            url,
            display,
            name,
            description: None,
            encryption_algorithm: Box::new(encryption_algorithm),
            authentication_algorithm: Box::new(authentication_algorithm),
            sa_lifetime_seconds: None,
            sa_lifetime_data: None,
            comments: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
        }
    }
}


