/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.1 (3.7)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableDataSourceRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedWritableDataSourceRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "source_url", skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "parameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Option<serde_json::Value>>,
    /// Patterns (one per line) matching files to ignore when syncing
    #[serde(rename = "ignore_rules", skip_serializing_if = "Option::is_none")]
    pub ignore_rules: Option<String>,
}

impl PatchedWritableDataSourceRequest {
    /// Adds support for custom fields and tags.
    pub fn new() -> PatchedWritableDataSourceRequest {
        PatchedWritableDataSourceRequest {
            name: None,
            r#type: None,
            source_url: None,
            enabled: None,
            description: None,
            comments: None,
            parameters: None,
            ignore_rules: None,
        }
    }
}


