/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.1 (3.7)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VirtualDisk : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VirtualDisk {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "virtual_machine")]
    pub virtual_machine: Box<crate::models::NestedVirtualMachine>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl VirtualDisk {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, virtual_machine: crate::models::NestedVirtualMachine, name: String, size: i32, created: Option<String>, last_updated: Option<String>) -> VirtualDisk {
        VirtualDisk {
            id,
            url,
            virtual_machine: Box::new(virtual_machine),
            name,
            description: None,
            size,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
        }
    }
}


