/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.1 (3.7)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WritableVirtualDiskRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WritableVirtualDiskRequest {
    #[serde(rename = "virtual_machine")]
    pub virtual_machine: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl WritableVirtualDiskRequest {
    /// Adds support for custom fields and tags.
    pub fn new(virtual_machine: i32, name: String, size: i32) -> WritableVirtualDiskRequest {
        WritableVirtualDiskRequest {
            virtual_machine,
            name,
            description: None,
            size,
            tags: None,
            custom_fields: None,
        }
    }
}


